# Generated by Django 4.1.7 on 2023-04-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.IntegerField()),
                ("city_name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Continent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "continent_name",
                    models.CharField(
                        help_text="Enter the name of continent",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("continent_img", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("continent", models.CharField(max_length=100, unique=True)),
                ("country_name", models.CharField(max_length=255, unique=True)),
                ("flag", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="DateWeather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255, unique=True)),
                ("date", models.DateField()),
                ("weather_status", models.CharField(max_length=255)),
                ("status_icon", models.CharField(max_length=255)),
                ("wind_speed", models.IntegerField()),
                ("humidity", models.IntegerField()),
                ("temperature", models.IntegerField()),
            ],
        ),
    ]
