# Generated by Django 4.1.7 on 2023-04-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="continent",
            name="continent_img",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="country",
            name="continent",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="country",
            name="flag",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="dateweather",
            name="city",
            field=models.CharField(max_length=255),
        ),
    ]
