# Generated by Django 4.1.7 on 2023-04-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0003_alter_city_country_alter_country_continent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="flag",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
