# Generated by Django 4.1.7 on 2023-04-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0004_alter_country_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dateweather",
            name="humidity",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="dateweather",
            name="status_icon",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="dateweather",
            name="temperature",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="dateweather",
            name="weather_status",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="dateweather",
            name="wind_speed",
            field=models.IntegerField(blank=True),
        ),
    ]
