# Generated by Django 4.1.7 on 2023-04-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0005_alter_dateweather_humidity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dateweather",
            name="humidity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="dateweather",
            name="temperature",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="dateweather",
            name="weather_status",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="dateweather",
            name="wind_speed",
            field=models.IntegerField(),
        ),
    ]
