# Generated by Django 4.1.7 on 2023-04-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0006_alter_dateweather_humidity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dateweather",
            name="humidity",
            field=models.IntegerField(help_text="Enter humidity value in percent(%)."),
        ),
        migrations.AlterField(
            model_name="dateweather",
            name="temperature",
            field=models.IntegerField(help_text="Enter temperature value in degrees."),
        ),
        migrations.AlterField(
            model_name="dateweather",
            name="wind_speed",
            field=models.IntegerField(help_text="Enter the wind speed value in km/h."),
        ),
    ]
