# Generated by Django 4.1.7 on 2023-04-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0007_alter_dateweather_humidity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="continent",
            name="continent_img",
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
