# Generated by Django 4.1.7 on 2023-04-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0008_alter_continent_continent_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="continent",
            name="continent_img",
            field=models.TextField(blank=True, max_length=1000000),
        ),
        migrations.AlterField(
            model_name="country",
            name="flag",
            field=models.CharField(blank=True, max_length=1000000),
        ),
        migrations.AlterField(
            model_name="dateweather",
            name="status_icon",
            field=models.CharField(blank=True, max_length=1000000),
        ),
    ]
