# Generated by Django 4.1.7 on 2023-04-23 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0009_alter_continent_continent_img_alter_country_flag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="city",
                to="my_app.country",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="continent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="country",
                to="my_app.continent",
            ),
        ),
        migrations.AlterField(
            model_name="dateweather",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dateweather",
                to="my_app.city",
            ),
        ),
    ]
